### PR TITLE
Automatically add comma before "թե"

### PR DESCRIPTION
**Pull request by HITMAnsOFT**
Handle "թե" similarly to other conjunctions.

### CODE REVIEW

**Comment by deimusmeister** [comment]
@HITMAnsOFT thanks for your contribution !
I think its grammatically not correct always to add comma before "թե", e.g. "վաղ թե ուշ"

here are some more examples
https://hy.wiktionary.org/wiki/%D5%A9%D5%A5

This PR will add comma always before "թե"

**Comment by deimusmeister** [comment]
@HITMAnsOFT Great contribution, thanks a lot !

**Comment by deimusmeister** [comment]
will be released over this weekend

**Comment by HITMAnsOFT** [comment]
I tried to add as many exceptions as I could remember. Are there others except "վաղ թե ուշ"?
For example, "լինել, թե չլինել" has a comma.

**Comment by HITMAnsOFT** [comment]
> @HITMAnsOFT Great contribution, thanks a lot !

Thanks for a great piece of software!

**Comment by deimusmeister** [comment]
> I tried to add as many exceptions as I could remember. Are there others except "վաղ թե ուշ"?
> For example, "լինել, թե չլինել" has a comma.

I had a look here,
https://hy.wiktionary.org/wiki/%D5%A9%D5%A5

**Pull request merged**
